// <auto-generated />
using System;
using LH.Main.Backend.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LH.Main.Backend.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920134254_AddMatchResults")]
    partial class AddMatchResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.GameServerSlot", b =>
                {
                    b.Property<string>("ServerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_match_id");

                    b.Property<string>("PublicHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("public_host");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer")
                        .HasColumnName("public_port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ServerId")
                        .HasName("pk_game_server_slots");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_game_server_slots_status");

                    b.ToTable("game_server_slots", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchQueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_match_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_match_queue_entries");

                    b.HasIndex("AssignedMatchId")
                        .HasDatabaseName("ix_match_queue_entries_assigned_match_id");

                    b.HasIndex("PlayerId", "Status")
                        .HasDatabaseName("ix_match_queue_entries_player_id_status");

                    b.ToTable("match_queue_entries", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_id");

                    b.HasKey("Id")
                        .HasName("pk_match_results");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_results_match_id");

                    b.ToTable("match_results", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchResultParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DamageApplied")
                        .HasColumnType("integer")
                        .HasColumnName("damage_applied");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("integer")
                        .HasColumnName("damage_taken");

                    b.Property<Guid>("MatchResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_result_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RewardCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_code");

                    b.Property<int>("SurvivedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("survived_seconds");

                    b.HasKey("Id")
                        .HasName("pk_match_result_participants");

                    b.HasIndex("MatchResultId")
                        .HasDatabaseName("ix_match_result_participants_match_result_id");

                    b.ToTable("match_result_participants", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_matches_server_id");

                    b.HasIndex("PlayerId", "Status")
                        .HasDatabaseName("ix_matches_player_id_status");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_id");

                    b.Property<string>("TicketHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ticket_hash");

                    b.HasKey("Id")
                        .HasName("pk_match_tickets");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_tickets_match_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_tickets_player_id");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_match_tickets_server_id");

                    b.HasIndex("TicketHash")
                        .IsUnique()
                        .HasDatabaseName("ix_match_tickets_ticket_hash");

                    b.ToTable("match_tickets", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("password_credentials", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.RewardTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("MatchResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_result_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RewardCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_code");

                    b.HasKey("Id")
                        .HasName("pk_reward_transactions");

                    b.HasIndex("MatchResultId");

                    b.HasIndex("PlayerId", "MatchResultId", "RewardCode")
                        .IsUnique()
                        .HasDatabaseName("ix_reward_transactions_player_result_reward");

                    b.ToTable("reward_transactions", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchQueueEntry", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.MatchSession", null)
                        .WithMany()
                        .HasForeignKey("AssignedMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_match_queue_entries_matches_assigned_match_id");

                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_queue_entries_users_player_id");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchResult", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.MatchSession", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchResultParticipant", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.MatchResult", null)
                        .WithMany()
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchSession", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_users_player_id");

                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.GameServerSlot", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_game_server_slots_server_id");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.MatchTicket", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.MatchSession", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_tickets_matches_match_id");

                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_tickets_users_player_id");

                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.GameServerSlot", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_tickets_game_server_slots_server_id");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", "User")
                        .WithOne("PasswordCredential")
                        .HasForeignKey("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.RewardTransaction", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.MatchResult", null)
                        .WithMany()
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.User", b =>
                {
                    b.Navigation("PasswordCredential");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
