// <auto-generated />
using System;
using LH.Main.Backend.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LH.Main.Backend.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("password_credentials", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", "User")
                        .WithOne("PasswordCredential")
                        .HasForeignKey("LH.Main.Backend.Api.Persistence.Entities.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", b =>
                {
                    b.HasOne("LH.Main.Backend.Api.Persistence.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LH.Main.Backend.Api.Persistence.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LH.Main.Backend.Api.Persistence.Entities.User", b =>
                {
                    b.Navigation("PasswordCredential");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
